# Generated by Django 2.2.2 on 2019-06-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='print',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
